### ISSUE TITLE
WEBSITE: Things that needs to be done

### ISSUE THREAD

**Issue by ChristinaELM** [aboestpetersen/HomeLocator#140]
Jamal asked for a pie chart showing how the 3 factors are distributed in the different cells.

**Comment by aboestpetersen** [comment]
- [x] ~~Pie Chart (not going to equal to 100% when added up, should we just stick to a bar chart? -ABP)~~
- [x] ~~Minimize Chart <div> element so that it is not visible at the start. Only maximizes when chart is populated. @aboestpetersen~~ KIND OF WORKING
- [ ] Clean up on 3 categories pages (maybe include sources)
- [x] Make the new code work
- [x] Do the presentation (gonna work on that later today)

Feel free to add and claim items on this list @marltrill, @Khorstaau, and @ChristinaELM.

@Khorstaau do you want your email and LinkedIn profile shared on the website (look at the bottom of the 'About' page for reference)?

**Comment by aboestpetersen** [comment]
> I think that the Pie chart won’t be 100% accurate, let’s stick with the bar chart!
> With Clean up the categories page you mean include data sources websites? Tried but for some reason it gives me an error. Could try again

Mainly the page discussing the three categories. For sources, we could have a section at the bottom of each page just called '<b>Sources</b>'. And they can be numbered. So citing a source would look like this [1]. And the number one would refer to the source at the bottom of the page.

**Comment by marltrill** [comment]
> > I think that the Pie chart won’t be 100% accurate, let’s stick with the bar chart!
> > With Clean up the categories page you mean include data sources websites? Tried but for some reason it gives me an error. Could try again
> 
> Mainly the page discussing the three categories. For sources, we could have a section at the bottom of each page just called 'Sources'. And they can be numbered. So citing a source would look like this [1]. And the number one would refer to the source at the bottom of the page.

Sounds good!!
